server.port: 8760
spring:
  application:
    name: service-config
  cloud.config:
    server.git:
      uri: https://github.com/yyyyyyyy/blog
      searchPaths: config
      username:
      password:
    label: master
eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/